# Use the Scatterwidget with AnnData from Notebook

This tutorial is an example of how to use the Napari-Spatialdata ScatterWidget from a notebook.

## Import packages and data

There are two options to install napari-spatialdata:

(1) Run `pip install napari-spatialdata`

or, 

(2) Clone this [repo](https://github.com/scverse/napari-spatialdata) and run `pip install -e .`

In [1]:
%load_ext autoreload
%autoreload 2

from napari_spatialdata import QtAdataScatterWidget
import squidpy as sq
import matplotlib.pyplot as plt

Load in the AnnData:

In [2]:
adata = sq.datasets.visium_hne_adata()

The following line is needed to initialize a widget without a QApplication:

In [3]:
%gui qt5

Open the ScatterWidget:

In [27]:
widget = QtAdataScatterWidget(adata)
widget.show()

2024-06-24 12:08:24.991 | INFO     | napari_spatialdata._scatterwidgets:_onOneClick:79 - <napari_spatialdata._scatterwidgets.ScatterListWidget object at 0x000001F5994611B0> should be skipping action
2024-06-24 12:08:27.951 | INFO     | napari_spatialdata._scatterwidgets:_onOneClick:81 - <napari_spatialdata._scatterwidgets.ScatterListWidget object at 0x000001F59906BB50> is calling action
2024-06-24 12:08:28.848 | INFO     | napari_spatialdata._scatterwidgets:_onClick:546 - Color data changed.
2024-06-24 12:08:28.849 | INFO     | napari_spatialdata._scatterwidgets:_onClick:561 - Prvious widgets cleared.
2024-06-24 12:08:28.929 | INFO     | napari_spatialdata._scatterwidgets:_onClick:572 - <class 'napari_spatialdata._scatterwidgets.DiscreteColorWidget'>
2024-06-24 12:08:28.929 | INFO     | napari_spatialdata._scatterwidgets:get_brushes:345 - Generating brushes...
2024-06-24 12:08:28.959 | INFO     | napari_spatialdata._scatterwidgets:plot:615 - Generating scatter plot...
2024-06-24 12:08:

In [7]:
widget.plot_widget.color_names

['Cortex_1',
 'Cortex_2',
 'Cortex_3',
 'Cortex_4',
 'Cortex_5',
 'Fiber_tract',
 'Hippocampus',
 'Hypothalamus_1',
 'Hypothalamus_2',
 'Lateral_ventricle',
 'Pyramidal_layer',
 'Pyramidal_layer_dentate_gyrus',
 'Striatum',
 'Thalamus_1',
 'Thalamus_2']

In [25]:
test = widget.plot_widget.discrete_color_widget.palette.map(1)*255
test

array([129.,  78.,  68., 255.], dtype=float32)

In [26]:
import pyqtgraph as pg
test_brush = pg.mkBrush(*test)
test_brush.color().getRgb()

(129, 78, 68, 255)

In [9]:
type(widget.plot_widget.discrete_color_widget)

napari_spatialdata._scatterwidgets.DiscreteColorWidget

In [87]:
from napari_spatialdata._scatterwidgets import DiscreteColorWidget

test = DiscreteColorWidget(widget.plot_widget._model, widget.plot_widget.color_data)
type(test)

napari_spatialdata._scatterwidgets.DiscreteColorWidget

In [57]:
test = widget.plot_widget.discrete_color_widget.widget().scene().items()
test

In [41]:
widget.plot_widget.addItem(test, row=0, col=2)

In [24]:
widget.plot_widget.discrete_color_widget

AttributeError: 'PlotWidget' object has no attribute 'discrete_color_widget'

In [10]:
lut = widget.plot_widget.create_lut_hist()
widget.plot_widget.addItem(lut, row=0, col=3)

2024-06-21 17:17:41.932 | INFO     | napari_spatialdata._scatterwidgets:get_brushes:351 - Generating brushes...
2024-06-21 17:17:41.973 | INFO     | napari_spatialdata._scatterwidgets:plot:565 - Generating scatter plot...


In [5]:
from napari_spatialdata._scatterwidgets import DiscreteColorWidget
from napari.utils.colormaps import label_colormap

In [7]:
from napari.utils.colormaps import label_colormap
napari_colormap = label_colormap(len(color_data['labels']))
napari_colormap.map(1)

array([0.5058824 , 0.30588236, 0.26666668, 1.        ], dtype=float32)

In [8]:
color_data = widget.color_widget.widget.data
color_widget = DiscreteColorWidget(widget.y_widget.widget._model, color_data)
#widget.plot_widget.addItem(test, row=0, col=3)

In [9]:
from pyqtgraph.Qt import QtWidgets, QtCore, QtGui
from napari.qt import get_current_stylesheet

# Get and set the napari stylesheet
# stylesheet = get_current_stylesheet()
# widget.setStyleSheet(stylesheet)

# Create a QGraphicsScene and add the custom widget
scene = QtWidgets.QGraphicsScene()
scene.addItem(color_widget)

# Create a QGraphicsView, set the scene, and make it scrollable
view = QtWidgets.QGraphicsView(scene)
view.setRenderHint(QtGui.QPainter.Antialiasing)
#view.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
view.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
view.setStyleSheet(get_current_stylesheet())
view.setStyleSheet(
    """
    QGraphicsView {
    border: none;
    background: rgb(0, 0, 0);
    }
    """
    )   

view_proxy = QtWidgets.QGraphicsProxyWidget()
view_proxy.setWidget(view)

widget.plot_widget.addItem(view_proxy, row=0, col=3)

2024-06-24 09:50:24.620 | INFO     | napari_spatialdata._scatterwidgets:get_brushes:351 - Generating brushes...
2024-06-24 09:50:24.660 | INFO     | napari_spatialdata._scatterwidgets:plot:565 - Generating scatter plot...
2024-06-24 09:50:25.189 | INFO     | napari_spatialdata._scatterwidgets:get_brushes:351 - Generating brushes...
2024-06-24 09:50:25.227 | INFO     | napari_spatialdata._scatterwidgets:plot:565 - Generating scatter plot...
2024-06-24 09:55:30.554 | INFO     | napari_spatialdata._scatterwidgets:plot:565 - Generating scatter plot...


In [27]:
print(get_current_stylesheet())

/* 
Styles in this file should only refer to built-in QtWidgets
It will be imported first, and styles declared in other files
may override these styles, but should only do so on
custom subclasses, object names, or properties.

might be possible to convert px to em by 1px = 0.0625em
*/



/* ----------------- QWidget ------------------ */
/* 

mappings between property and QPalette.ColorRole:
these colors can be looked up dynamically in widgets using, e.g
``widget.palette().color(QPalette.Window)``

background -> QPalette.Window/QPalette.Background
  background-color -> QPalette.Window/QPalette.Background
color -> QPalette.WindowText/QPalette.Foreground
selection-color -> QPalette.HighlightedText
selection-background-color -> QPalette.Highlight
alternate-background-color -> QPalette.AlternateBase

*/

QWidget {
  background-color: rgb(38, 41, 48);
  border: 0px;
  padding: 1px;
  margin: 0px;
  color: rgb(240, 241, 242);
  selection-background-color: rgb(134, 142, 147);
  selection-colo

In [8]:
widget.plot_widget.clear_plot()

In [5]:
widget.x_widget.widget.data

{'vec': array([102,  43,  19, ...,  30,  27,  51], dtype=int64)}

2024-06-20 10:54:44.242 | INFO     | napari_spatialdata._scatterwidgets:_onAction:54 - cluster
2024-06-20 10:54:45.940 | INFO     | napari_spatialdata._scatterwidgets:plot:464 - Generating scatter plot...
2024-06-20 10:54:51.003 | INFO     | napari_spatialdata._scatterwidgets:_onAction:54 - leiden
2024-06-20 10:54:51.843 | INFO     | napari_spatialdata._scatterwidgets:plot:464 - Generating scatter plot...
2024-06-20 10:54:54.024 | INFO     | napari_spatialdata._scatterwidgets:_onAction:54 - cluster
2024-06-20 10:54:54.915 | INFO     | napari_spatialdata._scatterwidgets:plot:464 - Generating scatter plot...
2024-06-20 10:55:01.478 | INFO     | napari_spatialdata._scatterwidgets:_onAction:54 - n_counts
2024-06-20 10:55:02.608 | INFO     | napari_spatialdata._scatterwidgets:plot:464 - Generating scatter plot...
2024-06-20 10:55:08.813 | INFO     | napari_spatialdata._scatterwidgets:_onAction:54 - spatial
2024-06-20 10:55:10.063 | INFO     | napari_spatialdata._scatterwidgets:plot:464 - Ge

In [17]:
widget.x_widget.widget._model.adata.obs.columns

Index(['in_tissue', 'array_row', 'array_col', 'n_genes_by_counts',
       'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts',
       'pct_counts_in_top_50_genes', 'pct_counts_in_top_100_genes',
       'pct_counts_in_top_200_genes', 'pct_counts_in_top_500_genes',
       'total_counts_mt', 'log1p_total_counts_mt', 'pct_counts_mt', 'n_counts',
       'leiden', 'cluster'],
      dtype='object')

In [12]:
widget.x_widget.widget._model.adata.obs['array_col']

AAACAAGTATCTCCCA-1    102
AAACAATCTACTAGCA-1     43
AAACACCAATAACTGC-1     19
AAACAGAGCGACTCCT-1     94
AAACCGGGTAGGTACC-1     28
                     ... 
TTGTTGTGTGTCAAGA-1     77
TTGTTTCACATCCAGG-1     42
TTGTTTCATTAGTCTA-1     30
TTGTTTCCATACAACT-1     27
TTGTTTGTGTAAATTC-1     51
Name: array_col, Length: 2688, dtype: int64

2024-06-18 16:53:46.064 | INFO     | napari_spatialdata._scatterwidgets:_onAction:48 - n_genes_by_counts
2024-06-18 16:53:48.679 | INFO     | napari_spatialdata._scatterwidgets:plot:459 - Generating scatter plot...
2024-06-18 16:53:49.038 | INFO     | napari_spatialdata._scatterwidgets:plot:459 - Generating scatter plot...
2024-06-18 16:54:03.857 | INFO     | napari_spatialdata._scatterwidgets:_onAction:48 - n_counts
2024-06-18 16:54:05.467 | INFO     | napari_spatialdata._scatterwidgets:plot:459 - Generating scatter plot...
2024-06-18 16:54:11.813 | INFO     | napari_spatialdata._scatterwidgets:_onAction:48 - pct_counts_in_top_100_genes
2024-06-18 16:54:12.614 | INFO     | napari_spatialdata._scatterwidgets:plot:459 - Generating scatter plot...
2024-06-18 16:54:23.241 | INFO     | napari_spatialdata._scatterwidgets:plot:459 - Generating scatter plot...


In [25]:
widget.x_widget.widget._model.get_obs('n_counts')

KeyError: '[None] not in index'

In [21]:
widget.x_widget.widget._model.adata.obs.columns

Index(['in_tissue', 'array_row', 'array_col', 'n_genes_by_counts',
       'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts',
       'pct_counts_in_top_50_genes', 'pct_counts_in_top_100_genes',
       'pct_counts_in_top_200_genes', 'pct_counts_in_top_500_genes',
       'total_counts_mt', 'log1p_total_counts_mt', 'pct_counts_mt', 'n_counts',
       'leiden', 'cluster'],
      dtype='object')

In [17]:
widget.x_widget.widget._getter

<bound method DataModel.get_obs of DataModel(events=<napari.utils.events.event.EmitterGroup object at 0x000002347D359B40>, _table_names=[], _active_table_name=None, _layer=None, _adata=AnnData object with n_obs × n_vars = 2688 × 18078
    obs: 'in_tissue', 'array_row', 'array_col', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'pct_counts_in_top_50_genes', 'pct_counts_in_top_100_genes', 'pct_counts_in_top_200_genes', 'pct_counts_in_top_500_genes', 'total_counts_mt', 'log1p_total_counts_mt', 'pct_counts_mt', 'n_counts', 'leiden', 'cluster'
    var: 'gene_ids', 'feature_types', 'genome', 'mt', 'n_cells_by_counts', 'mean_counts', 'log1p_mean_counts', 'pct_dropout_by_counts', 'total_counts', 'log1p_total_counts', 'n_cells', 'highly_variable', 'highly_variable_rank', 'means', 'variances', 'variances_norm'
    uns: 'cluster_colors', 'hvg', 'leiden', 'leiden_colors', 'neighbors', 'pca', 'rank_genes_groups', 'spatial', 'umap'
    obsm: 'X_pca', 'X_umap',

In [19]:
widget.x_widget.widget._model.get_obs('in_tissue')

KeyError: '[None] not in index'

2024-06-18 12:13:40.706 | INFO     | napari_spatialdata._scatterwidgets:_onAction:48 - 0610010F05Rik
2024-06-18 12:13:43.576 | INFO     | napari_spatialdata._scatterwidgets:_onAction:48 - 0610030E20Rik
2024-06-18 12:13:44.913 | INFO     | napari_spatialdata._scatterwidgets:plot:449 - Generating scatter plot...


In [17]:
widget.x_widget.selection_widget.currentText() == 'None'

True

In [13]:
widget.x_widget.widget._attr=None

In [54]:
import numpy as np
import pyqtgraph as pg
test = pg.pseudoScatter(widget.plot_widget.x_data)
#y, x = np.histogram(widget.plot_widget.x_data, bins=100)
widget.plot_widget.scatter_plot.plot(widget.plot_widget.x_data,test, fillLevel=0, symbolBrush=None)

In [51]:
widget.plot_widget.clear_plot()

In [50]:
widget.plot_widget.lut.plot.setVisible(True)
widget.plot_widget.lut.fillHistogram(True)

In [5]:
widget.plot_widget.lut.autoHistogramRange()

2024-06-13 11:51:36.676 | INFO     | napari_spatialdata._scatterwidgets:plot:353 - Generating scatter plot...
2024-06-13 11:51:42.372 | INFO     | napari_spatialdata._scatterwidgets:plot:353 - Generating scatter plot...
2024-06-13 11:51:44.780 | INFO     | napari_spatialdata._scatterwidgets:plot:353 - Generating scatter plot...
2024-06-13 11:51:46.340 | INFO     | napari_spatialdata._scatterwidgets:plot:353 - Generating scatter plot...
2024-06-13 11:51:58.916 | INFO     | napari_spatialdata._scatterwidgets:plot:353 - Generating scatter plot...


In [51]:
dir(widget.plot_widget.lut.plot)

['CacheMode',
 'DeviceCoordinateCache',
 'GraphicsItemChange',
 'GraphicsItemFlag',
 'GraphicsItemFlags',
 'ItemAcceptsInputMethod',
 'ItemChildAddedChange',
 'ItemChildRemovedChange',
 'ItemClipsChildrenToShape',
 'ItemClipsToShape',
 'ItemContainsChildrenInShape',
 'ItemCoordinateCache',
 'ItemCursorChange',
 'ItemCursorHasChanged',
 'ItemDoesntPropagateOpacityToChildren',
 'ItemEnabledChange',
 'ItemEnabledHasChanged',
 'ItemFlagsChange',
 'ItemFlagsHaveChanged',
 'ItemHasNoContents',
 'ItemIgnoresParentOpacity',
 'ItemIgnoresTransformations',
 'ItemIsFocusable',
 'ItemIsMovable',
 'ItemIsPanel',
 'ItemIsSelectable',
 'ItemMatrixChange',
 'ItemNegativeZStacksBehindParent',
 'ItemOpacityChange',
 'ItemOpacityHasChanged',
 'ItemParentChange',
 'ItemParentHasChanged',
 'ItemPositionChange',
 'ItemPositionHasChanged',
 'ItemRotationChange',
 'ItemRotationHasChanged',
 'ItemScaleChange',
 'ItemScaleHasChanged',
 'ItemSceneChange',
 'ItemSceneHasChanged',
 'ItemScenePositionHasChanged',
 

In [45]:
dir(widget.plot_widget.lut.plot)

['CacheMode',
 'DeviceCoordinateCache',
 'GraphicsItemChange',
 'GraphicsItemFlag',
 'GraphicsItemFlags',
 'ItemAcceptsInputMethod',
 'ItemChildAddedChange',
 'ItemChildRemovedChange',
 'ItemClipsChildrenToShape',
 'ItemClipsToShape',
 'ItemContainsChildrenInShape',
 'ItemCoordinateCache',
 'ItemCursorChange',
 'ItemCursorHasChanged',
 'ItemDoesntPropagateOpacityToChildren',
 'ItemEnabledChange',
 'ItemEnabledHasChanged',
 'ItemFlagsChange',
 'ItemFlagsHaveChanged',
 'ItemHasNoContents',
 'ItemIgnoresParentOpacity',
 'ItemIgnoresTransformations',
 'ItemIsFocusable',
 'ItemIsMovable',
 'ItemIsPanel',
 'ItemIsSelectable',
 'ItemMatrixChange',
 'ItemNegativeZStacksBehindParent',
 'ItemOpacityChange',
 'ItemOpacityHasChanged',
 'ItemParentChange',
 'ItemParentHasChanged',
 'ItemPositionChange',
 'ItemPositionHasChanged',
 'ItemRotationChange',
 'ItemRotationHasChanged',
 'ItemScaleChange',
 'ItemScaleHasChanged',
 'ItemSceneChange',
 'ItemSceneHasChanged',
 'ItemScenePositionHasChanged',
 

In [59]:
widget.plot_widget.lut.plot.setVisible(True)
widget.plot_widget.lut.plot.isVisible()

True

In [62]:
widget.plot_widget.lut.plot.paint()

In [32]:
import numpy as np
import pyqtgraph as pg

data_min = np.min(widget.plot_widget.data[2])
data_max = np.max(widget.plot_widget.data[2])
level_min, level_max = widget.plot_widget.lut.getLevels()
data = (widget.plot_widget.data[2] - data_min)/(data_max - data_min) * (level_max - level_min) + level_min
data = np.clip(data, 0, 1)

brush = [pg.mkBrush(*x) for x in widget.plot_widget.lut.gradient.colorMap().map(data)]
widget.plot_widget.scatter.setData(widget.plot_widget.data[0],widget.plot_widget.data[1],symbolBrush=brush)

In [26]:
widget.plot_widget.lut.gradient.colorMap().map(data)

array([[ 62,  75, 137, 255],
       [ 43, 115, 142, 255],
       [ 33, 165, 133, 255],
       ...,
       [ 33, 143, 141, 255],
       [ 32, 146, 140, 255],
       [ 68,  58, 131, 255]], dtype=uint8)

In [24]:
data

array([0.22610621, 0.38280392, 0.5884192 , ..., 0.4979358 , 0.5121363 ,
       0.17089015], dtype=float32)

In [15]:
widget.plot_widget.scatter.setSymbolBrush('r')

In [78]:
widget.plot_widget.lut.getLevels()

(0.08329004329004319, 0.40121212121212124)

In [10]:
widget.plot_widget.lut.gradient.colorMap

<bound method GradientEditorItem.colorMap of <pyqtgraph.graphicsItems.GradientEditorItem.GradientEditorItem object at 0x0000023608FE13F0>>

In [ ]:
[fn.mkBrush(*x) for x in self.colorMap.map(data)]

In [59]:
import pyqtgraph as pg
color_map = pg.colormap.get('viridis')
widget.plot_widget.lut.gradient.setColorMap(color_map)

In [45]:
for tick in widget.plot_widget.lut.gradient.ticks:
    widget.plot_widget.lut.gradient.removeTick(tick)


RuntimeError: dictionary changed size during iteration

In [66]:
color_map = pg.colormap.get('viridis')
widget.plot_widget.lut.gradient.setColorMap(color_map)
st = widget.plot_widget.lut.gradient.saveState()
st['ticksVisible'] = False
widget.plot_widget.lut.gradient.restoreState(st)

2024-06-10 15:19:29.248 | INFO     | napari_spatialdata._scatterwidgets:plot:351 - Generating scatter plot...
2024-06-10 15:19:47.469 | INFO     | napari_spatialdata._scatterwidgets:mousePressEvent:234 - Left press detected
2024-06-10 15:19:48.284 | INFO     | napari_spatialdata._scatterwidgets:mouseReleaseEvent:276 - Left button released.
2024-06-10 15:19:48.772 | INFO     | napari_spatialdata._scatterwidgets:mousePressEvent:234 - Left press detected
2024-06-10 15:19:49.647 | INFO     | napari_spatialdata._scatterwidgets:mouseReleaseEvent:276 - Left button released.
2024-06-10 15:19:50.155 | INFO     | napari_spatialdata._scatterwidgets:mousePressEvent:234 - Left press detected
2024-06-10 15:19:50.865 | INFO     | napari_spatialdata._scatterwidgets:mouseReleaseEvent:276 - Left button released.


In [63]:
widget.plot_widget.lut.gradient.restoreState(st)

In [60]:
#widget.plot_widget.lut.gradient.ticks = []
widget.plot_widget.lut.gradient.ticks_visible = False

In [42]:
st

{'mode': 'rgb',
 'ticks': [(0.0, (68, 1, 84, 255)),
  (0.00392156862745098, (68, 2, 86, 255)),
  (0.00784313725490196, (69, 4, 87, 255)),
  (0.011764705882352941, (69, 5, 89, 255)),
  (0.01568627450980392, (70, 7, 90, 255)),
  (0.0196078431372549, (70, 8, 92, 255)),
  (0.023529411764705882, (70, 10, 93, 255)),
  (0.027450980392156862, (70, 11, 94, 255)),
  (0.03137254901960784, (71, 13, 96, 255)),
  (0.03529411764705882, (71, 14, 97, 255)),
  (0.0392156862745098, (71, 16, 99, 255)),
  (0.043137254901960784, (71, 17, 100, 255)),
  (0.047058823529411764, (71, 19, 101, 255)),
  (0.050980392156862744, (72, 20, 103, 255)),
  (0.054901960784313725, (72, 22, 104, 255)),
  (0.058823529411764705, (72, 23, 105, 255)),
  (0.06274509803921569, (72, 24, 106, 255)),
  (0.06666666666666667, (72, 26, 108, 255)),
  (0.07058823529411765, (72, 27, 109, 255)),
  (0.07450980392156863, (72, 28, 110, 255)),
  (0.0784313725490196, (72, 29, 111, 255)),
  (0.08235294117647059, (72, 31, 112, 255)),
  (0.08627450

In [26]:
dir(widget.plot_widget.lut.gradient)

['CacheMode',
 'DeviceCoordinateCache',
 'GraphicsItemChange',
 'GraphicsItemFlag',
 'GraphicsItemFlags',
 'ItemAcceptsInputMethod',
 'ItemChildAddedChange',
 'ItemChildRemovedChange',
 'ItemClipsChildrenToShape',
 'ItemClipsToShape',
 'ItemContainsChildrenInShape',
 'ItemCoordinateCache',
 'ItemCursorChange',
 'ItemCursorHasChanged',
 'ItemDoesntPropagateOpacityToChildren',
 'ItemEnabledChange',
 'ItemEnabledHasChanged',
 'ItemFlagsChange',
 'ItemFlagsHaveChanged',
 'ItemHasNoContents',
 'ItemIgnoresParentOpacity',
 'ItemIgnoresTransformations',
 'ItemIsFocusable',
 'ItemIsMovable',
 'ItemIsPanel',
 'ItemIsSelectable',
 'ItemMatrixChange',
 'ItemNegativeZStacksBehindParent',
 'ItemOpacityChange',
 'ItemOpacityHasChanged',
 'ItemParentChange',
 'ItemParentHasChanged',
 'ItemPositionChange',
 'ItemPositionHasChanged',
 'ItemRotationChange',
 'ItemRotationHasChanged',
 'ItemScaleChange',
 'ItemScaleHasChanged',
 'ItemSceneChange',
 'ItemSceneHasChanged',
 'ItemScenePositionHasChanged',
 

In [37]:
widget.plot_widget.lut.gradient.getLookupTable()

TypeError: GradientEditorItem.getLookupTable() missing 1 required positional argument: 'nPts'

In [20]:
# Create a window
win = pg.GraphicsLayoutWidget(show=True)
win.setWindowTitle('Interactive Scatter Plot Coloring')

# Generate some data
n = 200  # number of points
x = np.random.normal(size=n)
y = np.random.normal(size=n)
values = np.random.normal(loc=0, scale=1, size=n)  # Property x to control colors

# Create histogram data
hist, bins = np.histogram(values, bins='auto')
histPlot = pg.PlotItem()
histogram = pg.BarGraphItem(x=bins[:-1], height=hist, width=np.diff(bins), brush='w')
histPlot.addItem(histogram)

# Create HistogramLUTItem
lut = pg.HistogramLUTItem()
lut.gradient.setColorMap(pg.colormap.get('viridis', source='matplotlib'))  # Choose any colormap
lut.setImageItem(histogram)  # We link HistogramLUTItem to the histogram visually

# Add items to layout
win.addItem(histPlot, row=0, col=0)
win.addItem(lut, row=0, col=1)

# Create scatter plot item
scatter = pg.ScatterPlotItem(size=10, pen=pg.mkPen(None))

AttributeError: 'BarGraphItem' object has no attribute 'setLookupTable'

: 

In [17]:
histPlot

In [6]:
widget.plot_widget.histPlot

AttributeError: 'PlotWidget' object has no attribute 'histPlot'

In [33]:
import pyqtgraph as pg

# Define new gradient stops
stops = {0.0: (255, 0, 0, 255),  # Red at 0%
         1.0: (0, 0, 255, 255)}  # Blue at 100%

# Set the gradient stops
widget.plot_widget.colorBar.setColorMap(pg.ColorMap(list(stops.keys()), list(stops.values())))

In [38]:
colormap = widget.plot_widget.colorBar.colorMap()

# Get the positions and colors from the colormap
positions, colors = colormap.getStops()

In [39]:
colors

array([[ 68,   1,  84, 255],
       [ 58,  82, 139, 255],
       [ 32, 144, 140, 255],
       [ 94, 201,  97, 255],
       [253, 231,  36, 255]], dtype=uint8)

In [30]:
widget.plot_widget.w4.setBackground('')

ColorMap(array([0, 1]), array([[0., 0., 0., 1.],       [1., 0., 0., 1.]]))

In [16]:
dir(widget.plot_widget.w4)

['AdjustIgnored',
 'AdjustToContents',
 'AdjustToContentsOnFirstShow',
 'AnchorUnderMouse',
 'AnchorViewCenter',
 'BoundingRectViewportUpdate',
 'Box',
 'CacheBackground',
 'CacheMode',
 'CacheModeFlag',
 'CacheNone',
 'DontAdjustForAntialiasing',
 'DontClipPainter',
 'DontSavePainterState',
 'DragMode',
 'DrawChildren',
 'DrawWindowBackground',
 'FullViewportUpdate',
 'HLine',
 'IgnoreMask',
 'MinimalViewportUpdate',
 'NoAnchor',
 'NoDrag',
 'NoFrame',
 'NoViewportUpdate',
 'OptimizationFlag',
 'OptimizationFlags',
 'PaintDeviceMetric',
 'Panel',
 'PdmDepth',
 'PdmDevicePixelRatio',
 'PdmDevicePixelRatioScaled',
 'PdmDpiX',
 'PdmDpiY',
 'PdmHeight',
 'PdmHeightMM',
 'PdmNumColors',
 'PdmPhysicalDpiX',
 'PdmPhysicalDpiY',
 'PdmWidth',
 'PdmWidthMM',
 'Plain',
 'Raised',
 'RenderFlag',
 'RenderFlags',
 'RubberBandDrag',
 'ScrollHandDrag',
 'Shadow',
 'Shadow_Mask',
 'Shape',
 'Shape_Mask',
 'SizeAdjustPolicy',
 'SmartViewportUpdate',
 'StyleMask',
 'StyledPanel',
 'Sunken',
 'VLine',
 '

In [9]:
import pyqtgraph as pg
t = pg.PolyLineROI([[1000,1000], [1000,2000], [2000,1000]], closed=True, removable = True)
widget.plot_widget.scatter_plot.addItem(t)

In [33]:
t = (None,None)
t is None

False

In [ ]:
t = pg.PolyLineROI([], closed=True, removable = True)

In [ ]:
t.getLocalHandlePositions()

In [ ]:
test = t.getHandles()
test[0]

In [ ]:
t.addSegment(2000,2000)

The widget:

In [ ]:
plt.imshow(widget.screenshot())
plt.axis('off')

Some examples of scatterplots:

In [ ]:
plt.imshow(widget.screenshot())
plt.axis('off')

In [ ]:
plt.imshow(widget.screenshot())
plt.axis('off')